version: '3.4'

services:
  property.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PropertyConnectionString=Server=orderdb;Database=PropertyDb;Encrypt=False;User Id=sa;Password=SwN12345678"  # for docker only
    ports:
      - "8000:80"
    depends_on:
      - orderdb
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
