version: '3.4'

services:
  property.api:
    image: ${DOCKER_REGISTRY-}propertyapi
    build:
      context: .
      dockerfile: Services/Property/Property.API/Dockerfile
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
